create table mate_code_table (
  id                        bigint              not null auto_increment                 comment '表Id',
  name                      varchar(300)        default ''                              comment '表名称',
  comment                   varchar(500)        default ''                              comment '表描述',
  class_name                varchar(100)        default ''                              comment '实体类名称',
  prefix                    varchar(100)        default ''                              comment '前缀名称',
  template                  varchar(200)        not null default 'base'                 comment '使用的模板',
  package_name              varchar(100)                                                comment '生成包路径',
  authority_name            varchar(30)                                                 comment '生成权限名',
  module_name               varchar(30)                                                 comment '生成模块名',
  business_name             varchar(30)                                                 comment '生成业务名',
  function_name             varchar(50)                                                 comment '生成功能名',
  author                    varchar(50)                                                 comment '生成功能作者',
  gen_type                  char(1)             not null default '0'                    comment '生成代码方式（0zip压缩包 1自定义路径）',
  gen_path                  varchar(200)        default '/'                             comment '后端生成路径',
  ui_path                   varchar(200)        default '/'                             comment '前端生成路径',
  options                   varchar(1000)                                               comment '其它生成选项',
  remark                    varchar(500)        default null                            comment '备注',
  create_by                 bigint              default null                            comment '创建者',
  create_time               datetime            default current_timestamp               comment '创建时间',
  update_by                 bigint              default null                            comment '更新者',
  update_time               datetime            on update current_timestamp             comment '更新时间',
  primary key (id)
) engine=innodb auto_increment=1  DEFAULT CHARSET=utf8mb4 comment = '代码生成基础表';

create table mate_code_column (
  id                        bigint              not null auto_increment                 comment '字段Id',
  table_id                  varchar(64)         not null                                comment '归属表Id',
  name                      varchar(200)                                                comment '列名称',
  comment                   varchar(500)                                                comment '列描述',
  type                      varchar(100)                                                comment '列类型',
  java_type                 varchar(500)                                                comment 'JAVA类型',
  java_field                varchar(200)                                                comment 'JAVA字段名',
  is_pk                     tinyint(1)          not null default 0                      comment '主键字段（1是 0否）',
  is_increment              tinyint(1)          not null default 0                      comment '自增字段（1是 0否）',
  is_required               tinyint(1)          not null default 0                      comment '必填字段（1是 0否）',
  is_view                   tinyint(1)          not null default 0                      comment '查看字段（1是 0否）',
  is_insert                 tinyint(1)          not null default 0                      comment '新增字段（1是 0否）',
  is_edit                   tinyint(1)          not null default 0                      comment '编辑字段（1是 0否）',
  is_list                   tinyint(1)          not null default 0                      comment '列表字段（1是 0否）',
  is_query                  tinyint(1)          not null default 0                      comment '查询字段（1是 0否）',
  is_unique                 tinyint(1)          not null default 0                      comment '唯一字段（1是 0否）',
  is_import                 tinyint(1)          not null default 0                      comment '导入字段（1是 0否）',
  is_export                 tinyint(1)          not null default 0                      comment '导出字段（1是 0否）',
  is_hide                   tinyint(1)          not null default 0                      comment '隐藏字段（1是 0否）',
  is_cover                  tinyint(1)          not null default 0                      comment '覆盖字段（1是 0否）',
  query_type                varchar(200)        default 'EQ'                            comment '查询方式（等于、不等于、大于、小于、范围）',
  html_type                 varchar(200)                                                comment '显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）',
  dict_type                 varchar(200)        default ''                              comment '字典类型',
  sort                      int unsigned        not null default 0                      comment '显示顺序',
  create_by                 bigint              default null                            comment '创建者',
  create_time               datetime            default current_timestamp               comment '创建时间',
  update_by                 bigint              default null                            comment '更新者',
  update_time               datetime            on update current_timestamp             comment '更新时间',
  primary key (id)
) engine=innodb auto_increment=1 DEFAULT CHARSET=utf8mb4 comment = '代码生成字段表';